version: '3'
services:
  server:
    build:
     context: .
     dockerfile: Dockerfile
    volumes:
      - ".:/home/rstudio/work"
    ports:
      - "8787:8787"
    restart: always
    tty: true
    stdin_open: true
    environment:
      - ROOT=TRUE
      - USERID=rstudio
      - PASSWORD=password
